#
# DeGirum GitHub CI build script
# Copyright 2023 DeGirum Corporation
#
# PySDKExamples merge workflow: runs tests on PySDKExamples install scripts and jupyter notebooks
#

name: CI Merge

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    # Setup matrix on Ubuntu, Windows and MacOS runners
    strategy:
      # do not abort other jobs on job failure
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019]
        include:
          - default_shell: bash -eo pipefail -l {0}
          - os: windows-2019
            default_shell: cmd

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.default_shell }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # bash install
      - name: run bash install script
        if: ${{ contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos') }}
        run: |
          ./install.sh
          eval "$(conda shell.bash hook)"
          conda activate degirum
          python -c 'import degirum; print(degirum.__version__)'
          jupyter --version
          pip install pytest pytest-xdist
          python -m pytest -n auto -vs --token=${{ secrets.CS_TOKEN }}

      # batch install
      - name: run batch install script
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          install.bat

      - name: run batch install script
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          dir %USERPROFILE%\miniconda3
          set "%PATH%=%USERPROFILE%\miniconda3;%PATH%"
          conda activate degirum
          python -c 'import degirum; print(degirum.__version__)'
          jupyter --version
          pip install pytest pytest-xdist
          python -m pytest -n auto -vs --token=${{ secrets.CS_TOKEN }}
